"""
Knowledge retrieval tool for the Helix specialist agent.
Interfaces with the VectorStore to provide grounded context from documentation.
"""
from app.rag.vector_store import vector_store

async def search_docs(query: str, k: int = 5, product_area: str | None = None) -> str:
    """
    Search the vector store for the top-k relevant document chunks.
    
    Args:
        query: The semantic search query (usually generated by the agent).
        k: Number of chunks to retrieve (default 5).
        product_area: Optional metadata filter (e.g., 'billing', 'ci-cd').
        
    Returns:
        A formatted string containing document IDs, sources, and content.
    """
    # Stage 1: Vector Search + Reranking (handled inside vector_store)
    chunks = await vector_store.search(query, k=k)
    
    # Stage 2: Metadata Filtering
    # If the agent specified a product area, we filter the results here.
    if product_area:
        chunks = [c for c in chunks if c.metadata.get("product_area") == product_area]
    
    # Handle empty results gracefully
    if not chunks:
        return "No relevant documentation found."

    # Stage 3: Formatting for LLM consumption
    # We include chunk IDs in brackets (e.g., [chunk_123]) to facilitate citation tracking.
    parts = []
    for chunk in chunks:
        parts.append(
            f"[{chunk.chunk_id}] (score: {chunk.score:.2f}, source: {chunk.metadata.get('source')})\n"
            f"{chunk.content}"
        )
    return "\n\n---\n\n".join(parts)
